// Multiple journals on one device. Your own journal is the default; "sample lives" (famous
// people and entities, generated by the model) each live in their OWN IndexedDB database and
// their OWN namespaced settings, so nothing a sample does can touch your real journal.
//
// The active journal is an id in localStorage ("" = your own). Switching reloads the page: the
// db layer reads the id at load and opens that journal's database, and the per-journal settings
// (title, birth year, decade grouping) are read from namespaced keys.

const BASE_DB = "summarizing-journal";

export function activeJournalId() { return localStorage.getItem("active-journal") || ""; }
export function isSampleJournal() { return !!activeJournalId(); }

// The IndexedDB database name for a journal. Your own keeps the original name (so existing data
// is untouched); a sample gets its own suffixed database.
export function dbNameFor(id = activeJournalId()) { return id ? `${BASE_DB}~${id}` : BASE_DB; }

// A per-journal localStorage key. Your own journal uses the bare key (back-compat with settings
// you already set); a sample suffixes the key so its title/birth-year/grouping stand apart.
export function jkey(base, id = activeJournalId()) { return id ? `${base}::${id}` : base; }

// Switch to a journal (by id; "" = your own) and reload so every layer re-reads it.
export function switchJournal(id) {
  if ((id || "") === activeJournalId()) return;
  localStorage.setItem("active-journal", id || "");
  location.reload();
}

// A registry of sample journals that have been created on this device, so the gallery can show
// which are ready and list any custom ones the user generated. Each: { id, title, subtitle, kind }.
const REGISTRY_KEY = "journals-registry";
export function listJournals() {
  try { const a = JSON.parse(localStorage.getItem(REGISTRY_KEY) || "[]"); return Array.isArray(a) ? a : []; }
  catch { return []; }
}
export function registerJournal(entry) {
  const all = listJournals().filter((j) => j.id !== entry.id);
  all.push(entry);
  localStorage.setItem(REGISTRY_KEY, JSON.stringify(all));
}
export function journalExists(id) { return listJournals().some((j) => j.id === id); }

// Delete a sample journal entirely: its database, its registry row, and its namespaced settings.
export function deleteJournal(id) {
  if (!id) return; // never the user's own
  try { indexedDB.deleteDatabase(dbNameFor(id)); } catch { /* ignore */ }
  const all = listJournals().filter((j) => j.id !== id);
  localStorage.setItem(REGISTRY_KEY, JSON.stringify(all));
  for (const base of ["journal-title", "birth-year", "year-grouping", "baked"]) localStorage.removeItem(jkey(base, id));
}

// Slugify a subject name into a stable journal id ("The Beatles" → "the-beatles").
export function slugify(name) {
  return String(name).toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);
}
